# Generated by Django 4.2.5 on 2023-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('spotify_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('spotify_id', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('spotify_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('access_token', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.TextField()),
                ('spotify_id', models.TextField(primary_key=True, serialize=False)),
                ('danceability', models.FloatField(default=None, null=True)),
                ('energy', models.FloatField(default=None, null=True)),
                ('key', models.IntegerField(default=None, null=True)),
                ('loudness', models.FloatField(default=None, null=True)),
                ('mode', models.IntegerField(default=None, null=True)),
                ('speechiness', models.FloatField(default=None, null=True)),
                ('acousticness', models.FloatField(default=None, null=True)),
                ('instrumentalness', models.FloatField(default=None, null=True)),
                ('liveness', models.FloatField(default=None, null=True)),
                ('valence', models.FloatField(default=None, null=True)),
                ('tempo', models.FloatField(default=None, null=True)),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('cover', models.TextField()),
                ('artists', models.ManyToManyField(to='home.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotify_id', models.TextField(default=None, null=True)),
                ('name', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('songs', models.ManyToManyField(to='home.song')),
                ('songs_filtered_by_blacklist', models.ManyToManyField(related_name='songs_filtered_by_blacklist', to='home.song')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(default='')),
                ('playlists', models.ManyToManyField(to='home.playlist')),
                ('songs_from_users', models.ManyToManyField(to='home.song')),
                ('users', models.ManyToManyField(to='home.user')),
            ],
        ),
    ]
