# Generated by Django 4.2.3 on 2023-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
