# Generated by Django 4.2.3 on 2023-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_song_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='spotify_id',
            field=models.TextField(default=None, null=True),
        ),
    ]
