# Generated by Django 4.2.3 on 2023-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_playlist_description_alter_playlist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
