# Generated by Django 4.2.3 on 2023-09-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_song_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
    ]
