# Generated by Django 4.2.3 on 2023-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_artist_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
